# Generated by Django 4.0.4 on 2022-05-05 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Manager ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Postal'),
        ),
        migrations.AlterField(
            model_name='location',
            name='unit_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unit No.'),
        ),
    ]
