# Generated by Django 4.0.4 on 2022-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accounttypes',
            options={'verbose_name': 'Account Type', 'verbose_name_plural': 'Account Types'},
        ),
        migrations.AlterField(
            model_name='account',
            name='contact',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='accounttypes',
            name='is_fulltimer',
            field=models.BooleanField(default=False, verbose_name='FullTime Employee'),
        ),
    ]
