# Generated by Django 4.0.4 on 2022-05-05 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(verbose_name='Period')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid Status')),
                ('paid_on', models.DateField(verbose_name='Paid Date')),
                ('paid_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Paid By')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff ID')),
            ],
            options={
                'verbose_name': 'Time Sheet',
                'verbose_name_plural': 'Time Sheets',
            },
        ),
        migrations.CreateModel(
            name='TimeSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DurationField(blank=True, null=True, verbose_name='Total Hours')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('job_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobuser', verbose_name="Staff's Job ID")),
                ('timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.timesheet', verbose_name='Time Sheet ID')),
            ],
            options={
                'verbose_name': 'Time Sheet Item',
                'verbose_name_plural': 'Time Sheet Items',
            },
        ),
    ]
