# Generated by Django 4.0.4 on 2022-05-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_jobuser_check_in_alter_jobuser_check_out'),
        ('timesheet', '0004_alter_timesheet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetitem',
            name='job_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobuser', verbose_name="Staff's Job ID"),
        ),
    ]
