# Generated by Django 4.0.4 on 2022-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_is_deleted_alter_jobuser_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobuser',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in Time'),
        ),
        migrations.AlterField(
            model_name='jobuser',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-out Time'),
        ),
    ]
