# Generated by Django 4.0.4 on 2022-05-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jobuser_check_in_alter_jobuser_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobuser',
            name='check_in',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Check-in Time'),
        ),
        migrations.AlterField(
            model_name='jobuser',
            name='check_out',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Check-out Time'),
        ),
    ]
